### ISSUE TITLE
cats-effect 3

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#392]
Hiya,

The lib is still on version 2, to upgrade to version 3 is see that Monix is behind in upgrading. Would you mind if open a PR dropping these modules?

The thing we like about your library it's based on sttp. This means you can plug in any backend you would like to to interact with keycloak. This could be:

- Try
- Future
- ZIO
- Monix
- cats-effect IO

It's nice to have modules setup, but it creates a burden to maintain

**Comment by StuartJ45** [comment]
Hi Mark,

I do agree that the modules are a burden to maintain, but I'm not sure of the alternative.

I don't think it's as simple as swapping out sttp backends, at least with the current setup.
We need to be able to compose sttp calls and use functionality that the above monads provide.
This means that, as far as I'm aware, we can't create a single abstract module that can work with any monad, as we need a more specific monad implementation so that we have access to `flatMap`, error handling functions, etc.
This is also why we'd require a new Zio module (#366) in order to properly support the use of this library in a Zio project.

You'll see that the base admin API module (keycloak4s-admin) is somewhat abstracted, by restricting the monad type to one that supports cats Concurrent. This way, we can compose calls and add error handling and retry logic.
